# includes/excludes all rules by default
default: true

# 4-space list indentation works best with MkDocs
MD007:
  indent: 4

# Remove line length limit
MD013: false

# Allow us to skip levels of headings
MD001: false

# Allow us to use emphasis on whole lines.
MD036: false

# Allow us to use lower-level headings to start files
MD041: false

# Fenced code blocks in tabbed views will flag
MD046: false
