site_name: "Travel Model Two Python Package: tm2py"
site_url: https://bayareametro.github.io/tm2py
repo_url: https://github.com/bayareametro/tm2py
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: 
    - Server Setup: server-setup.md
    - Installing tm2py: install.md
    - Running tm2: run.md
  - Codebase:
    - Architecture: architecture.md
    - API Documentation: api.md
  - Input & Output:
    - Input: inputs.md
    - Output: outputs.md
  - Contributing:
    - Development: contributing/development.md
    - Documentation: contributing/documentation.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          setup_commands:
           - import sys
           - from unittest.mock import MagicMock as mock
           - sys.path.append('../')  
           - sys.modules["inro"] = mock()
           - sys.modules["inro.emme"] = mock()
           - sys.modules["inro.emme.database"] = mock()
           - sys.modules["inro.emme.database.emmebank"] = mock()
           - sys.modules["inro.emme.database.scenario"] = mock()
           - sys.modules["inro.emme.database.matrix"] = mock()
           - sys.modules["inro.emme.network"] = mock()
           - sys.modules["inro.emme.network.node"] = mock()
           - sys.modules["inro.emme.desktop"] = mock()
           - sys.modules["inro.emme.desktop.app"] = mock()
           - sys.modules["inro.modeller"] = mock()
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: true
            show_source: true
            heading_level: 3
      # custom_templates: templates
      watch:
        - tm2py
  - search
  - mermaid2

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - meta
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.smartsymbols
  - smarty
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  
