[scenario]
    year = 2015
    verify = false
    maz_landuse_file = "inputs\\landuse\\maz_data.csv"

[run]
    start_iteration = 0
    end_iteration = 1

    create_tod_scenarios = true
    active_modes = true
    air_passenger = true
    highway_maz_maz = [ true, true ]
    highway = [ true, true ]
    transit = [ true, true ]
    drive_access = [ true, true ]
    household = [ true ]
    internal_external = [ true ]
    truck = [ true ]

[[periods]]
    name = "ea"
    length_hours = 3
    highway_capacity_factor = 3
    emme_scenario_id = 11
[[periods]]
    name = "am"
    length_hours = 4
    highway_capacity_factor = 3.65
    emme_scenario_id = 12
[[periods]]
    name = "md"
    length_hours = 5
    highway_capacity_factor = 5
    emme_scenario_id = 13
[[periods]]
    name = "pm"
    length_hours = 4
    highway_capacity_factor = 3.65
    emme_scenario_id = 14
[[periods]]
    name = "ev"
    length_hours = 8
    highway_capacity_factor = 8
    emme_scenario_id = 15

[household]
    highway_demand_file = "demand_matrices\\highway\\household\\TAZ_Demand_{period}.omx"
    transit_demand_file = "demand_matrices\\transit\\TAP_Demand_{set}_{period}.omx"

[air_passenger]
    highway_demand_file = "demand_matrices\\highway\\air_passenger\\tripsAirPax{period}.omx"
    input_demand_folder = "inputs\\nonres"
    reference_start_year = "2007"
    reference_end_year = "2035"
    [[air_passenger.demand_aggregation]]
        result_class_name = "da"
        src_group_name = "DA"
        access_modes = [ "ES", "PK", "RN", "TX", "LI",]
    [[air_passenger.demand_aggregation]]
        result_class_name = "sr2"
        src_group_name = "S2"
        access_modes = [ "ES", "PK", "RN", "TX", "LI",]
    [[air_passenger.demand_aggregation]]
        result_class_name = "sr3"
        src_group_name = "S3"
        access_modes = [ "ES", "PK", "RN", "TX", "LI", "VN", "HT", "CH",]

[internal_external]
    highway_demand_file = "demand_matrices\\highway\\internal_external\\tripsIx{period}.omx"
    input_demand_file = "inputs\\nonres\\IXDaily2006x4.may2208.new.omx"
    reference_year = 2005
    toll_choice_time_coefficient = -0.088
    value_of_time = 18.93
    shared_ride_2_toll_factor = 0.5714285714285714
    shared_ride_3_toll_factor = 0.4
    operating_cost_per_mile = 17.23

[truck]
    highway_demand_file = "demand_matrices\\highway\\commercial\\tripstrk{period}.omx"
    # skim_file = "skims_matrices\\highway\\taz\\commercial\\COM_HWYSKIM{period}_taz.omx"
    k_factors_file = "inputs\\nonres\\truck_kfactors_taz.csv"
    friction_factors_file = "inputs\\nonres\\truckFF.dat"
    value_of_time = 37.87
    operating_cost_per_mile = 31.28
    toll_choice_time_coefficient = -0.088
    max_balance_iterations = 999
    max_balance_relative_error = 0.0001

[active_modes]
    emme_scenario_id = 1
    [[active_modes.shortest_path_skims]]
        mode = "walk"
        roots = "MAZ"
        leaves = "MAZ"
        max_dist_miles = 3
        output = "skim_matrices\\non_motorized\\ped_distance_maz_maz.txt"
    [[active_modes.shortest_path_skims]]
        mode = "walk"
        roots = "MAZ"
        leaves = "TAP"
        max_dist_miles = 0.5
        output = "skim_matrices\\non_motorized\\ped_distance_maz_tap.txt"
    [[active_modes.shortest_path_skims]]
        mode = "bike"
        roots = "MAZ"
        leaves = "MAZ"
        max_dist_miles = 3
        output = "skim_matrices\\non_motorized\\bike_distance_maz_maz.txt"
    [[active_modes.shortest_path_skims]]
        mode = "bike"
        roots = "MAZ"
        leaves = "TAP"
        max_dist_miles = 3
        output = "skim_matrices\\non_motorized\\bike_distance_maz_tap.txt"
    [[active_modes.shortest_path_skims]]
        mode = "bike"
        roots = "TAZ"
        leaves = "TAZ"
        output = "skim_matrices\\non_motorized\\bike_distance_taz_taz.txt"
    [[active_modes.shortest_path_skims]]
        mode = "walk"
        roots = "TAP"
        leaves = "TAP"
        max_dist_miles = 0.5
        output = "skim_matrices\\non_motorized\\ped_distance_tap_tap.txt"

[highway]
    output_skim_path = "skim_matrices\\highway\\HWYSKM{period}_taz.omx"
    relative_gap = 0.0005
    max_iterations = 0
    # labels entire highway network (any of the classes) + MAZ connectors
    generic_highway_mode_code = "c"
    # include other MAZs to estimate density (pop+jobs*2.5)/acres for each MAZ
    area_type_buffer_dist_miles = 0.5
    [highway.tolls]
        file_path = "inputs\\hwy\\tolls.csv"
        src_vehicle_group_names = ["da", "s2",  "s3",  "vsm", "sml", "med", "lrg"]
        # the dst_vehicle_group_names is used in the class group suffix for the
        # highway.classes toll attribute names and the skims names
        dst_vehicle_group_names = ["da", "sr2", "sr3", "vsm", "sml", "med", "lrg"]
        tollbooth_start_index = 11
    [highway.maz_to_maz]
        mode_code = "x"
        excluded_links = [ "is_toll_da", "is_sr",]
        operating_cost_per_mile = 18.93
        value_of_time = 17.23
        input_maz_highway_demand_file = "demand_matrices\\highway\\maz_demand\\auto_{period}_MAZ_AUTO_{number}_{period}.omx"
        output_skim_file = "skim_matrices\\highway\\HWYSKIM_MAZMAZ_DA.csv"
        skim_period = "md"
        max_skim_cost = 11.0
            # based on ~= 5 miles @ 40 mph = 11
            #           = time + (0.6 / vot) * (dist * opcost) 
            #           = 5 / 40 * 60 + (0.6 / 17.23) * (5 * 18.93)
    [[highway.classes]]
        name = "da"
        description = "drive alone"
        mode_code = "d"
        excluded_links = [ "is_toll_da", "is_sr",]
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@bridgetoll_da"
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_da",]
        [[highway.classes.demand]]
            source = "household"
            name = "SOV_GP_{period}"
        [[highway.classes.demand]]
            source = "air_passenger"
            name = "da"
        [[highway.classes.demand]]
            source = "internal_external"
            name = "da"
    [[highway.classes]]
        name = "sr2"
        description = "shared ride 2"
        mode_code = "e"
        excluded_links = [ "is_toll_sr2", "is_sr3",]
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@bridgetoll_sr2"
        toll_factor = 0.5714285714285714
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_sr2", "hovdist",]
        [[highway.classes.demand]]
            source = "household"
            name = "SR2_GP_{period}"
            factor = 0.5714285714285714
        [[highway.classes.demand]]
            source = "household"
            name = "SR2_HOV_{period}"
            factor = 0.5714285714285714
        [[highway.classes.demand]]
            source = "air_passenger"
            name = "sr2"
        [[highway.classes.demand]]
            source = "internal_external"
            name = "sr2"
    [[highway.classes]]
        name = "sr3"
        description = "shared ride 3+"
        mode_code = "f"
        excluded_links = [ "is_toll_sr3",]
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@bridgetoll_sr3"
        toll_factor = 0.4
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_sr3", "hovdist",]
        [[highway.classes.demand]]
            source = "household"
            name = "SR3_GP_{period}"
            factor = 0.4
        [[highway.classes.demand]]
            source = "household"
            name = "SR3_HOV_{period}"
            factor = 0.4
        [[highway.classes.demand]]
            source = "air_passenger"
            name = "sr3"
        [[highway.classes.demand]]
            source = "internal_external"
            name = "sr3"
    [[highway.classes]]
        name = "trk"
        description = "truck"
        mode_code = "t"
        excluded_links = [ "is_toll_vsm", "is_toll_sml", "is_toll_med", "is_sr",]
        value_of_time = 37.87
        operating_cost_per_mile = 31.28
        toll = "@bridgetoll_sml"
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_vsm", "bridgetoll_sml", "bridgetoll_med",]
        [[highway.classes.demand]]
            source = "truck"
            name = "vsmtrk"
        [[highway.classes.demand]]
            source = "truck"
            name = "smltrk"
        [[highway.classes.demand]]
            source = "truck"
            name = "medtrk"
    [[highway.classes]]
        name = "lrgtrk"
        description = "large truck"
        mode_code = "l"
        excluded_links = [ "is_toll_lrg", "is_auto_only",]
        value_of_time = 37.87
        operating_cost_per_mile = 31.28
        toll = "@bridgetoll_lrg"
        passenger_car_equivalent = 2.0
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_lrg",]
        [[highway.classes.demand]]
            source = "truck"
            name = "lrgtrk"
            factor = 2.0
    [[highway.classes]]
        name = "datoll"
        description = "drive alone toll"
        mode_code = "D"
        excluded_links = [ "is_sr",]
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@valuetoll_da + @bridgetoll_da"
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_da", "valuetoll_da", "tolldist",]
        [[highway.classes.demand]]
            source = "household"
            name = "SOV_PAY_{period}"
        [[highway.classes.demand]]
            source = "internal_external"
            name = "datoll"
    [[highway.classes]]
        name = "sr2toll"
        description = "shared ride 2 toll"
        mode_code = "E"
        excluded_links = [ "is_sr3",]
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@valuetoll_sr2 + @bridgetoll_sr2"
        toll_factor = 0.5714285714285714
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_sr2", "valuetoll_sr2", "hovdist", "tolldist",]
        [[highway.classes.demand]]
            source = "household"
            name = "SR2_PAY_{period}"
            factor = 0.5714285714285714
        [[highway.classes.demand]]
            source = "internal_external"
            name = "sr2toll"
    [[highway.classes]]
        name = "sr3toll"
        description = "shared ride 3+ toll"
        mode_code = "F"
        excluded_links = []
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@valuetoll_sr3 + @bridgetoll_sr3"
        toll_factor = 0.4
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_sr3", "valuetoll_sr3", "hovdist", "tolldist",]
        [[highway.classes.demand]]
            source = "household"
            name = "SR3_PAY_{period}"
            factor = 0.4
        [[highway.classes.demand]]
            source = "internal_external"
            name = "sr3toll"
    [[highway.classes]]
        name = "trktoll"
        description = "truck toll"
        mode_code = "T"
        excluded_links = [ "is_sr",]
        value_of_time = 37.87
        operating_cost_per_mile = 31.28
        toll = "@valuetoll_sml + @bridgetoll_sml"
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_vsm", "bridgetoll_sml", "bridgetoll_med", "valuetoll_vsm", "valuetoll_sml", "valuetoll_med",]
        [[highway.classes.demand]]
            source = "truck"
            name = "vsmtrktoll"
        [[highway.classes.demand]]
            source = "truck"
            name = "smltrktoll"
        [[highway.classes.demand]]
            source = "truck"
            name = "medtrktoll"
    [[highway.classes]]
        name = "lrgtrktoll"
        description = "large truck toll"
        mode_code = "L"
        excluded_links = [ "is_auto_only", "is_sr",]
        value_of_time = 37.87
        operating_cost_per_mile = 31.28
        pce = 2.0
        toll = "@valuetoll_lrg + @bridgetoll_lrg"
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_lrg", "valuetoll_lrg",]
        [[highway.classes.demand]]
            source = "truck"
            name = "lrgtrktoll"
            factor = 2.0


[transit]
    apply_msa_demand = false
    value_of_time = 16.2
    effective_headway_source = "hdw"
    initial_wait_perception_factor = 1.5
    transfer_wait_perception_factor = 3.0
    walk_perception_factor = 2.0
    in_vehicle_perception_factor = 1.0
    initial_boarding_penalty = 10
    transfer_boarding_penalty = 10
    max_transfers = 3
    output_skim_path = "skim_matrices\\transit\\transit_skims_{period}.omx"
    fares_path = "inputs\\trn\\fares.far"
    fare_matrix_path = "inputs\\trn\\fareMatrix.txt"
    # max expected transfer distance for mode-to-mode transfer fare table generation
    fare_max_transfer_distance_miles = 3.0
    use_fares = false

[emme]
    num_processors = "max-1"
    all_day_scenario_id = 1
    project_path = "emme_project\\mtc_emme.emp"
    highway_database_path = "emme_project\\Database_highway\\emmebank"
    active_database_paths = [ "emme_project\\Database_active_south\\emmebank", "emme_project\\Database_active_north\\emmebank" ]
    transit_database_path = "emme_project\\Database_transit\\emmebank"
