####################################
#   OBSERVED DATA CONFIGURATION    #
####################################

[remote_io]
    folder_root = "~/Box Sync/"

[transit]
    on_board_survey_file = "Survey_Database_122717/survey.feather"
    reduced_summaries_file = "Survey_Database_122717/acceptance-criteria-reductions.csv"
