####################################
#   OBSERVED DATA CONFIGURATION    #
####################################

[remote_io]
    #obs_folder_root = "/Users/wsp/Box Sync/"
    obs_folder_root = "//corp.pbwan.net/us/CentralData/DCCLDA00/Standard/sag/projects/MTC/Acceptance_Criteria/counts/"
[transit]
    on_board_survey_file = "Survey_Database_122717/onboard-survey-trip-list.feather"
    reduced_summaries_file = "Survey_Database_122717/acceptance-criteria-reductions.csv"
    reduced_access_summary_file = "Survey_Database_122717/acceptance-criteria-access-summaries-year-2015.csv"
    bart_boardings_file = "bart-typical-weekday/BART Through Time Typical Weekday.csv"
[census]
    ctpp_2012_2016_file = "CTPP20122016/A302100 - Total Workers (1) (Workers 16 years and over).csv"
    vehicles_by_block_group_file = "Census/ACSDT5Y2017.B08201-Data.csv"
    census_geographies_shapefile = "Census/tl_2010_06_bg10.shp"
    census_geographies_pickle = "Census/tl_2010_06_bg10.pickle"
    census_tract_centroids_geojson = "Census/tl_2010_tract_centroids.geojson"
[roadway]
    pems_traffic_count_file = "pems_period.csv"
    pems_truck_traffic_count_file = "pems_truck.period.csv"
    reduced_summaries_file = "reduced_traffic_counts.csv"
