[scenario]
    year = 2015
    verify = false
    maz_landuse_file = "inputs\\landuse\\maz_data.csv"

[run]
    start_iteration = 0
    end_iteration = 1
    start_component = ""
    initial_components = ["create_tod_scenarios", "active_modes", "air_passenger", "highway_maz_maz", "highway", "transit"]
    global_iteration_components = ["household", "internal_external", "truck", "highway_maz_maz", "highway", "transit"]
    final_components = []

[[time_periods]]
    name = "ea"
    length_hours = 3
    highway_capacity_factor = 3
    emme_scenario_id = 11
[[time_periods]]
    name = "am"
    length_hours = 4
    highway_capacity_factor = 3.65
    emme_scenario_id = 12
[[time_periods]]
    name = "md"
    length_hours = 5
    highway_capacity_factor = 5
    emme_scenario_id = 13
[[time_periods]]
    name = "pm"
    length_hours = 4
    highway_capacity_factor = 3.65
    emme_scenario_id = 14
[[time_periods]]
    name = "ev"
    length_hours = 8
    highway_capacity_factor = 8
    emme_scenario_id = 15

[household]
    highway_demand_file = "demand_matrices\\highway\\household\\TAZ_Demand_{period}.omx"
    transit_demand_file = "demand_matrices\\transit\\TAP_Demand_{set}_{period}.omx"

[air_passenger]
    highway_demand_file = "demand_matrices\\highway\\air_passenger\\tripsAirPax{period}.omx"
    input_demand_folder = "inputs\\nonres"
    reference_start_year = "2007"
    reference_end_year = "2035"
    [[air_passenger.demand_aggregation]]
        result_class_name = "da"
        src_group_name = "DA"
        access_modes = [ "ES", "PK", "RN", "TX", "LI",]
    [[air_passenger.demand_aggregation]]
        result_class_name = "sr2"
        src_group_name = "S2"
        access_modes = [ "ES", "PK", "RN", "TX", "LI",]
    [[air_passenger.demand_aggregation]]
        result_class_name = "sr3"
        src_group_name = "S3"
        access_modes = [ "ES", "PK", "RN", "TX", "LI", "VN", "HT", "CH",]

[internal_external]
    highway_demand_file = "demand_matrices\\highway\\internal_external\\tripsIx{period}.omx"
    input_demand_file = "inputs\\nonres\\IXDaily2006x4.may2208.new.omx"
    reference_year = 2005
    toll_choice_time_coefficient = -0.088
    value_of_time = 18.93
    shared_ride_2_toll_factor = 0.5714285714285714
    shared_ride_3_toll_factor = 0.4
    operating_cost_per_mile = 17.23

[truck]
    highway_demand_file = "demand_matrices\\highway\\commercial\\tripstrk{period}.omx"
    # skim_file = "skims_matrices\\highway\\taz\\commercial\\COM_HWYSKIM{period}_taz.omx"
    k_factors_file = "inputs\\nonres\\truck_kfactors_taz.csv"
    friction_factors_file = "inputs\\nonres\\truckFF.dat"
    value_of_time = 37.87
    operating_cost_per_mile = 31.28
    toll_choice_time_coefficient = -0.088
    max_balance_iterations = 999
    max_balance_relative_error = 0.0001

[active_modes]
    emme_scenario_id = 1
    [[active_modes.shortest_path_skims]]
        mode = "walk"
        roots = "MAZ"
        leaves = "MAZ"
        max_dist_miles = 3
        output = "skim_matrices\\non_motorized\\ped_distance_maz_maz.txt"
    [[active_modes.shortest_path_skims]]
        mode = "walk"
        roots = "MAZ"
        leaves = "TAP"
        max_dist_miles = 0.5
        output = "skim_matrices\\non_motorized\\ped_distance_maz_tap.txt"
    [[active_modes.shortest_path_skims]]
        mode = "bike"
        roots = "MAZ"
        leaves = "MAZ"
        max_dist_miles = 3
        output = "skim_matrices\\non_motorized\\bike_distance_maz_maz.txt"
    [[active_modes.shortest_path_skims]]
        mode = "bike"
        roots = "MAZ"
        leaves = "TAP"
        max_dist_miles = 3
        output = "skim_matrices\\non_motorized\\bike_distance_maz_tap.txt"
    [[active_modes.shortest_path_skims]]
        mode = "walk"
        roots = "TAP"
        leaves = "TAP"
        max_dist_miles = 0.5
        output = "skim_matrices\\non_motorized\\ped_distance_tap_tap.txt"

[highway]
    output_skim_path = "skim_matrices\\highway\\HWYSKM{period}_taz.omx"
    relative_gap = 0.0005
    max_iterations = 0
    # labels entire highway network (any of the classes) + MAZ connectors
    generic_highway_mode_code = "c"
    # include other MAZs to estimate density (pop+jobs*2.5)/acres for each MAZ
    area_type_buffer_dist_miles = 0.5
    [highway.tolls]
        file_path = "inputs\\hwy\\tolls.csv"
        src_vehicle_group_names = ["da", "s2",  "s3",  "vsm", "sml", "med", "lrg"]
        # the dst_vehicle_group_names is used in the class group suffix for the
        # highway.classes toll attribute names and the skims names
        dst_vehicle_group_names = ["da", "sr2", "sr3", "vsm", "sml", "med", "lrg"]
        tollbooth_start_index = 11
    [highway.maz_to_maz]
        mode_code = "x"
        excluded_links = [ "is_toll_da", "is_sr",]
        operating_cost_per_mile = 18.93
        value_of_time = 17.23
        input_maz_highway_demand_file = "demand_matrices\\highway\\maz_demand\\auto_{period}_MAZ_AUTO_{number}_{period}.omx"
        output_skim_file = "skim_matrices\\highway\\HWYSKIM_MAZMAZ_DA.csv"
        skim_period = "md"
        max_skim_cost = 11.0
            # based on ~= 5 miles @ 40 mph = 11
            #           = time + (0.6 / vot) * (dist * opcost) 
            #           = 5 / 40 * 60 + (0.6 / 17.23) * (5 * 18.93)
    [[highway.classes]]
        name = "da"
        description = "drive alone"
        mode_code = "d"
        excluded_links = [ "is_toll_da", "is_sr",]
        value_of_time = 18.93
        operating_cost_per_mile = 17.23
        toll = "@bridgetoll_da"
        skims = [ "time", "dist", "freeflowtime", "bridgetoll_da",]
        [[highway.classes.demand]]
            source = "household"
            name = "SOV_GP_{period}"
        [[highway.classes.demand]]
            source = "air_passenger"
            name = "da"
        [[highway.classes.demand]]
            source = "internal_external"
            name = "da"
    [[highway.capclass_lookup]]
        capclass = 0
        capacity = 0
        free_flow_speed = 0
        critical_speed = 0

    [[highway.capclass_lookup]]
        capclass = 1
        capacity = 2050
        free_flow_speed = 55
        critical_speed = 18.835

    [[highway.capclass_lookup]]
        capclass = 2
        capacity = 1450
        free_flow_speed = 40
        critical_speed = 25.898

    [[highway.capclass_lookup]]
        capclass = 3
        capacity = 1450
        free_flow_speed = 30
        critical_speed = 11.772

    [[highway.capclass_lookup]]
        capclass = 4
        capacity = 900
        free_flow_speed = 20
        critical_speed = 4.709

    [[highway.capclass_lookup]]
        capclass = 5
        capacity = 900
        free_flow_speed = 20
        critical_speed = 11.772

    [[highway.capclass_lookup]]
        capclass = 6
        capacity = 600
        free_flow_speed = 15
        critical_speed = 47.087

    [[highway.capclass_lookup]]
        capclass = 7
        capacity = 600
        free_flow_speed = 15
        critical_speed = 7.063

    [[highway.capclass_lookup]]
        capclass = 8
        capacity = 2050
        free_flow_speed = 18
        critical_speed = 9.417

    [[highway.capclass_lookup]]
        capclass = 9
        capacity = 0
        free_flow_speed = 0
        critical_speed = 25.898

    [[highway.capclass_lookup]]
        capclass = 10
        capacity = 0
        free_flow_speed = 18
        critical_speed = 14.126

[transit]
    apply_msa_demand = false
    value_of_time = 16.2
    effective_headway_source = "hdw"
    initial_wait_perception_factor = 1.5
    transfer_wait_perception_factor = 3.0
    walk_perception_factor = 2.0
    in_vehicle_perception_factor = 1.0
    initial_boarding_penalty = 10
    transfer_boarding_penalty = 10
    max_transfers = 3
    output_skim_path = "skim_matrices\\transit\\transit_skims_{period}.omx"
    fares_path = "inputs\\trn\\fares.far"
    fare_matrix_path = "inputs\\trn\\fareMatrix.txt"
    # max expected transfer distance for mode-to-mode transfer fare table generation
    fare_max_transfer_distance_miles = 3.0
    use_fares = false
    # for TAZ instead of TAPs
    override_connector_times = true
    input_connector_access_times_path = "inputs\\trn\\estimated_taz_access_connectors.csv"
    input_connector_egress_times_path = "inputs\\trn\\estimated_taz_egress_connectors.csv"
    output_stop_usage_path = "inputs\\trn\\stop_usage_{period}.csv"

    [[transit.modes]]
        mode_id = "w"
        name = "walk"
        type = "WALK"
        assign_type = "AUX_TRANSIT"
        speed_miles_per_hour = 3.0
    [[transit.modes]]
        mode_id = "a"
        name = "access"
        type = "ACCESS"
        assign_type = "AUX_TRANSIT"
        speed_miles_per_hour = 3.0
    [[transit.modes]]
        mode_id = "e"
        name = "egress"
        type = "EGRESS"
        assign_type = "AUX_TRANSIT"
        speed_miles_per_hour = 3.0
    [[transit.modes]]
        mode_id = "b"
        name = "local_bus"
        type = "LOCAL"
        assign_type = "TRANSIT"
    [[transit.modes]]
        mode_id = "x"
        name = "exp_bus"
        type = "PREMIUM"
        assign_type = "TRANSIT"
    [[transit.modes]]
        mode_id = "f"
        name = "ferry"
        type = "PREMIUM"
        assign_type = "TRANSIT"
    [[transit.modes]]
        mode_id = "l"
        name = "light_rail"
        type = "PREMIUM"
        assign_type = "TRANSIT"
    [[transit.modes]]
        mode_id = "h"
        name = "heavy_rail"
        type = "PREMIUM"
        assign_type = "TRANSIT"
    [[transit.modes]]
        mode_id = "r"
        name = "comm_rail"
        type = "PREMIUM"
        assign_type = "TRANSIT"

    [[transit.vehicles]]
        vehicle_id = 12 
        mode = "b"
        name = ""
        auto_equivalent = 2.0
        seated_capacity = 1 
        total_capacity = 2
    [[transit.vehicles]]
        vehicle_id = 14 
        mode = "b"
        name = ""
        auto_equivalent = 2.0
        seated_capacity = 1 
        total_capacity = 2

[emme]
    num_processors = "max-1"
    all_day_scenario_id = 1
    project_path = "emme_project\\mtc_emme.emp"
    highway_database_path = "emme_project\\Database_highway\\emmebank"
    active_database_paths = [ "emme_project\\Database_active_south\\emmebank", "emme_project\\Database_active_north\\emmebank" ]
    transit_database_path = "emme_project\\Database_transit_taz\\emmebank"
