---
title: "Summarize Journey Level Assumptions"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
network_dir <- "../../travel-model-two-networks/data/processed/"
interim_dir <- "../data/interim/"
crosswalk_dir <- "../examples/temp_acceptance/"

journey_filename <- paste0(interim_dir, "transit_links_summary.csv")
crosswalk_filename <- paste0(crosswalk_dir, "gtfs_to_tm2_mode_crosswalk.csv")

output_filename <- paste0(interim_dir, "journey-levels-for-tableau.csv")
```

# Parameters
```{r parameters}
VERSION <- "version_11"
```


# Data Reads
```{r read}
routes_df <- read_csv(paste0(network_dir, VERSION, "/", "routes.txt"), col_types = "ccccciccccccccci")
crosswalk_df <- read_csv(paste0(crosswalk_filename), col_types = cols(.default = col_character()))
journey_df <- read_csv(paste0(journey_filename), col_types = cols(.default = col_character()))
```

# Reductions 
```{r reductions}
output_df <- journey_df %>%
  filter(!str_starts(Line, "pnr_")) %>%
  separate(., Line, into = c("agency_id", "agency_name", "route_id", "time_period", "direction", "shape_id"), sep = "_", extra = "drop", fill = "left", remove = FALSE) %>%
  select(., route_id, emme_temp_mode = Mode) %>%
  mutate(route_id = as.integer(route_id)) %>%
  distinct(.) %>%
  left_join(., select(routes_df, route_id, agency_raw_name, route_type), by = c("route_id")) %>%
  mutate(route_type = paste0(route_type)) %>%
  select(-route_id) %>%
  distinct(.) %>%
  left_join(., distinct(crosswalk_df, agency_raw_name, agency_name, route_type, technology = TM2_line_haul_name, fare_system = TM2_faresystem), by = c("agency_raw_name", "route_type")) %>%
  select(emme_temp_mode, agency_name, technology, fare_system)

```

# Write
```{r write}
write_csv(output_df, file = output_filename, na = "")
```

