name: Run Tests

on: 
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        python-version: ${{ matrix.python-version }}
        name: "${{ matrix.python-version }}.${{ github.head_ref }}.${{ github.sha }}"
    - name: Test with pytest
      run: |
        pytest -s -m "not skipci"
