name: Clean Docs for Deleted References
on: 
  delete:

env:
  PYTHON_VERSION: 3.8

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Set up Python $PYTHON_VERSION
      uses: actions/setup-python@v2
      with:
        python-version: $PYTHON_VERSION
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mike
    - name: Configure Git user
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Delete defunct docs versions
      run: |
        echo "Deleting ${{ github.event.ref_name }} version from docs"
        mike delete ${{ github.event.ref_name }}